---
title: "Untitled"
author: "RN7"
date: "September 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r message=FALSE}
library(polite)
library(rvest)
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(extrafont)
loadfonts()
```



```{r}
url <- "https://en.wikipedia.org/wiki/Japan%E2%80%93South_Korea_football_rivalry"

session <- bow(url)

jpn_kor_df_raw <- scrape(session) %>% 
  html_nodes(xpath = "//*[@id='mw-content-text']/div/table[3]") %>% 
  .[[1]] %>% 
  html_table()
```

- separate score for HOME - AWAY
- separate score for PKs
- check for neutral >>> Tokyo, Yokohama, etc. == JAPAN, Seoul, Daegu, etc. == Korea, ELSE == neutral
- vertical lollipop chart

```{r}
jpn_kor_df_raw %>% glimpse()
```

- need to use iconv() to fix "-" as different types of "-" characters in the score variable...!

```{r}
jpn_kor_df_clean <- jpn_kor_df_raw %>% 
  janitor::clean_names() %>% 
  mutate(pen = score %>% 
           iconv(from = "UTF-8", to = "ASCII//TRANSLIT") %>% 
           str_extract("\\([^()]+\\)"),
         pen = gsub("[(PK)]", "", pen),
         score = score %>% 
           iconv(from = "UTF-8", to = "ASCII//TRANSLIT") %>% 
           str_remove("\\(.*\\)"),
         date = dmy(date)) %>% 
  separate("score", into = c("home_score", "away_score"), sep = "-") %>%
  separate("pen", into = c("home_score_pen", "away_score_pen"), sep = "-") %>% 
  mutate_at(vars(contains("score")), as.numeric)

jpn_kor_df_clean <- jpn_kor_df_clean %>% 
  mutate(date = replace(date, number == 53, "1993-10-25"))

```



```{r}
jpn_kor_test <- jpn_kor_df_clean %>% select(date, home_team, home_score, away_team, away_score)

jpn_kor_test <- jpn_kor_test %>% 
  unite("home", c("home_team", "home_score")) %>% 
  unite("away", c("away_team", "away_score")) %>% 
  gather(key = team_type, value = team, -date) %>% 
  mutate(goal = str_extract(team, "[^_]+$")) %>% 
  mutate(team = str_remove(team, "_[0-9]")) %>% 
  arrange(desc(date))
  
  #separate(value, into = c("team", "goals"), extra = "merge")

jpn_kor_test %>% 
  filter(date > "2000-01-01") %>% 
  ggplot(aes(date, goal)) +
  geom_point(aes(group = date, color = team)) +
  geom_path(aes(group = date, x = date, y = goal)) +
  theme_minimal()
  #scale_x_continuous(breaks = 10) +
  scale_x_date(limits = c(as.Date("2000-01-01"), as.Date("2018-01-01")),
               date_breaks = "1 day")
```


```{r}
jpn_kor_fix <- jpn_kor_test %>% 
  mutate(num = as.integer(factor(date)))

jpn_kor_fix %>% 
  ggplot(aes(num, goal)) +
  geom_point(aes(group = num, color = team)) +
  geom_path(aes(group = num, x = num, y = goal)) +
  scale_x_continuous(breaks = 10)
  scale_x_date(limits = c(as.Date("1954-01-01"), as.Date("1955-01-01")),
               date_breaks = "1 day")
  
```






```{r, fig.width=10, fig.height=7, fig.showtext=TRUE}
jpn_kor_df_clean %>% 
  mutate(winner = case_when(
    home_score > away_score & home_team == "Japan" ~ "Japan",
    away_score > home_score & away_team == "Japan" ~ "Japan",
    home_score > away_score & home_team == "South Korea" ~ "South Korea",
    away_score > home_score & away_team == "South Korea" ~ "South Korea",
    home_score == away_score & home_score_pen > away_score_pen & home_team == "Japan" ~ 
      "Japan",
    home_score == away_score & home_score_pen < away_score_pen & away_team == "Japan" ~ 
      "Japan",
    home_score == away_score & home_score_pen > away_score_pen & home_team == "South Korea" ~ 
      "South Korea",
    home_score == away_score & home_score_pen < away_score_pen & away_team == "South Korea" ~ 
      "South Korea",
    TRUE ~ "Draw"
  )) %>% 
  mutate(pen = case_when(
    home_score == away_score & home_score_pen > away_score_pen & home_team == "Japan" ~ 
      "Pen: Japan",
    home_score == away_score & home_score_pen < away_score_pen & away_team == "Japan" ~ 
      "Pen: Japan",
    home_score == away_score & home_score_pen > away_score_pen & home_team == "South Korea" ~ 
      "Pen: South Korea",
    home_score == away_score & home_score_pen < away_score_pen & away_team == "South Korea" ~ 
      "Pen: South Korea",
    TRUE ~ "non-PK"
  )) %>% 
  select(date, home_team, home_score, away_team, away_score, winner, pen) %>% 
  unite("home", c("home_team", "home_score")) %>% 
  unite("away", c("away_team", "away_score")) %>% 
  gather(key = team_type, value = team, -date, - winner, -pen) %>% 
  mutate(goal = str_extract(team, "[^_]+$")) %>% 
  mutate(team = str_remove(team, "_[0-9]")) %>% 
  arrange(desc(date)) -> jpn_kor_final
  
```


```{r fig.width=10, fig.height=7, fig.showtext=TRUE}
library(emo)
line_vals <- c("Japan" = "blue", "South Korea" = "red",
               "Draw" = "grey")

breaks <- as.Date(c("2000-01-01", "2005-01-01", "2010-01-01", "2015-01-01", "2018-01-01"))
labs <- c("2000", "2005", "2010", "2015", "2018")

flag_data <- data.frame(
  x = c(),
  y = c(),
  team = c("japan", "south korea")
) %>% 
  mutate(image = team %>% countrycode::countrycode(., origin = "country.name", 
                                                   destination = "iso2c")) %>% 
  select(-team)




jpn_kor_final %>% 
  filter(date > "2000-01-01") %>% 
  ggplot() +
  geom_path(aes(group = date, x = date, y = goal, color = winner), 
            size = 1.5,
            show.legend = TRUE) +
  scale_color_manual(name = "", 
                     values = line_vals) +
  # Japan
  geom_point(data = jpn_kor_final %>% 
               filter(date > "2000-01-01", team == "Japan", 
                      winner == "Japan" | winner == "South Korea",
                      pen == "non-PK"), 
             aes(x = date, y = goal, group = date), 
             color = "blue", size = 4) +
  # Korea
  geom_point(data = jpn_kor_final %>% 
               filter(date > "2000-01-01", team == "South Korea", 
                      winner == "Japan" | winner == "South Korea",
                      pen == "non-PK"),
             aes(x = date, y = goal, group = date), 
             color = "red", size = 4) +
  # Draw
  geom_point(data = jpn_kor_final %>% 
               filter(date > "2000-01-01", winner == "Draw"),
             aes(x = date, y = goal, group = date), 
             color = "grey", size = 4.5, shape = 17) +
  geom_point(data = jpn_kor_final %>% 
               filter(date > "2000-01-01", pen == "Pen: Japan"),
             aes(x = date, y = goal, group = date), 
             color = "blue", size = 4.5, shape = 17) +
  geom_point(data = jpn_kor_final %>% 
               filter(date > "2000-01-01", pen == "Pen: South Korea"),
             aes(x = date, y = goal, group = date), 
             color = "red", size = 4.5, shape = 17) +
  scale_x_date(limits = c(as.Date("2000-01-01"), as.Date("2018-01-01")),
               breaks = breaks, labels = labs,
               expand = c(0.05, 0.05)) +
  scale_y_discrete(expand = c(0.05, 0.2)) +
  labs(title = "Japan vs. South Korea: The Eternal East Asian Rivalry since 2000",
       x = NULL, y = "Goals Scored") +
  # Custom annotations:
  geom_segment(aes(x = as.Date("2007-07-28"), xend = as.Date("2007-08-30"),
                   y = 1, yend = 1.2)) +
  geom_segment(aes(x = as.Date("2011-01-25"), xend = as.Date("2011-03-10"),
                   y = 3, yend = 3.2)) +
  annotate(geom = "text",
           x = as.Date("2000-08-30"),
           y = 5,
           label = glue::glue(
         "        : 5 Wins,         : 6 Wins, 5 Draws"),
         hjust = 0,
         family = "Roboto Condensed") +
  annotate(geom = "label",
           x = as.Date("2007-07-28"), 
           y = 1.25,
           label = "2007 Asian Cup: 3rd Place Match", 
           hjust = 0, 
           family = "Roboto Condensed") +
  annotate(geom = "label",
           x = as.Date("2011-01-25"), 
           y = 3.3,
           label = "2011 Asian Cup: Semi-Final", 
           family = "Roboto Condensed",
           hjust = 0) +
  theme_minimal() +
  theme(text = element_text(family = "Roboto Condensed"),
        title = element_text(size = 20),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 16),
        legend.title = element_blank(),
        legend.position = c(0.1, 0.8),
        legend.box.background = element_rect(color = "black"))




ggimage::geom_flag(data = flag_data,
                     aes(x = x, y = y,
                         image = image),       
                     size = c(0.08, 0.08))
```


```{r fig.width=20, fig.height=10}
## ALL TIME
jpn_kor_final %>% 
  ggplot() +
  geom_point(data = jpn_kor_final %>% 
               filter(team == "Japan", winner != "Draw"), 
             aes(x = date, y = goal, group = date), 
             color = "blue", size = 3) +
  geom_point(data = jpn_kor_final %>% 
               filter(team == "South Korea", winner != "Draw"),
             aes(x = date, y = goal, group = date), 
             color = "red", size = 3) +
  geom_point(data = jpn_kor_final %>% 
               filter(winner == "Draw"),
             aes(x = date, y = goal, group = date), 
             color = "grey", size = 3.5) +
  geom_path(aes(group = date, x = date, y = goal, color = winner)) +
  scale_color_manual(values = line_vals) +
  scale_x_date(limits = c(as.Date("1954-01-01"), as.Date("2018-01-01")),
               date_breaks = "1 years", expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  theme_minimal() 
```

