---
title: "Untitled"
author: "RN7"
date: "June 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Uniform animation
https://guyabel.com/post/football-kits/

ex. Liverpool 


```{r}
library(rvest)
library(dplyr)
library(purrr)
library(stringr)
library(magick)

url <- "http://www.historicalkits.co.uk/Liverpool/Liverpool.htm"

#kits
#div.float:nth-child(2)
#div.float:nth-child(3) > img:nth-child(2)
#div.float:nth-child(2)
#div.float:nth-child(2) > img:nth-child(2)
#div.float:nth-child(67)
#div.float:nth-child(2) > img:nth-child(2)
#div.float:nth-child(2) > img:nth-child(2)
#.float p , .float img
#/html/body/div[2]/div[4]/div[2]/div[2]/div[3]/img
#div.float:nth-child(4) > img:nth-child(1)
#html body div#master div#bodywrap div#maincol div.content div.float img

url %>% 
  read_html() %>% 
  html_nodes(".float p , .float img") %>% 
  html_attr("src")


url %>% 
  read_html() %>% 
  html_nodes(".float img") %>% 
  html_attr("src")

url %>% 
  read_html() %>% 
  html_nodes(".float p , .float img") %>% 
  html_text() %>% 
  c(., NA) %>% 
  .[-1]



scrape_img_url <- function(html){
  html %>%
    html_nodes(".float p , .float img") %>%
    html_attr("src") %>%
    tbl_df() %>%
    set_names("img_url") %>%
    mutate(label = html %>% 
             html_nodes(".float p , .float img") %>%
             html_text() %>%
             c(., NA) %>%
             .[-1])
}


d1 <- read_html("http://www.historicalkits.co.uk/Liverpool/Liverpool.htm") %>%
  scrape_img_url() %>%
  filter(str_detect(string = img_url, pattern = "/Liverpool"),
         !str_detect(string = img_url, pattern = "unknown")) %>%
  mutate(
    label = str_replace_all(string = label,
                            pattern = "[:alpha:]|\\s", 
                            replacement = "")
  )
# some wrong labels... 



# 2000s

d2 <- d1 %>% 
  slice(46:58)

# download img
kits <- d2 %>% 
  mutate(img_url = paste0("http://www.historicalkits.co.uk", img_url)) %>% 
  select(img_url) %>% 
  map(image_read) %>% 
  set_names("img")

# morph

kits_ani <- image_morph(c(kits$img[1], kits$img[1]), frames = 4)
kits_ani



seq_along(kits$img)
2:length(kits$img)

seq_along(kits$img) - 1

# save vector of seq_along() 
# map image_morph with vectors of kits$img

kits_len <- seq_along(kits$img)

2:length(kits$img)


kits %>% 
  map(kits_len, function(x) image_morph(.$img - 1, .$img), frame = 5)


for (i in 2:length(kits$img)) {
  
  kits_morph0 <- image_morph(c(kits$img[i - 1], kits$img[i]), frames = 4)
  
  kits_morph1 <- image_morph(c(kits$img[i], kits$img[i]), frames = 4)
  
  kits_ani <- c(kits_ani, kits_morph0)
  
  kits_ani <- c(kits_ani, kits_morph1)
  
}

# animation

kits_ani %>% 
  image_animate(fps = 10) %>% 
  image_write(path = "liv_2000s.gif")

```


## Japan World Cup uniforms

```{r}
library(magick)

japan_kits <- list.files(path = "./japan_kits/", pattern = "*.gif", full.names = TRUE) %>% 
  map(image_read) %>% 
  image_join()

# no join
japan_kits2 <- list.files(path = "./japan_kits/", pattern = "*.gif", full.names = TRUE) %>% 
  map(image_read) 

japan_kits2 <- japan_kits2 %>% set_names(rep("img", 6))

japan_kits <- list(img = japan_kits) # turn into list with "img" as name
# subset [1] to [6] in this. so can image_morph() call each and previous

japan_seq2 <- seq_along(japan_kits2)


#
japan_ani <- image_morph(c(japan_kits$img[1], japan_kits$img[1]), frame = 10)

kits_morph_j0 <- 2:6 %>% 
  map(~ image_morph(c(japan_kits$img[.x-1], japan_kits$img[.x]), frames = 10)) %>% 
  image_join()

kits_morph_j1 <- 2:6 %>% 
  map(~ image_morph(c(japan_kits$img[.x], japan_kits$img[.x]), frames = 10)) %>% 
  image_join()

jkits_ani <- c(japan_ani, kits_morph_j0)
# jkits_ani <- c(jkits_ani, kits_morph_j1)  #  need to integrate PAUSE with morph anims

jkits_ani %>% 
  image_animate(fps = 10) %>% 
  image_write(path = "japan_kit.gif")

```































