---
title: "Untitled"
author: "RN7"
date: "December 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
pacman::p_load(tidyverse, scales, lubridate, ggrepel, stringi,
               glue, extrafont, rvest, ggtextures, cowplot, countrycode, ggimage)
# necessary for Roboto Condensed font
loadfonts()

```


```{r}
ac_top_scorers <- data.frame(
  player = c("Ali Daei", "Ali Daei", "Ali Daei",
             "Lee Dong Gook", "Lee Dong Gook",
             "Naohiro Takahara", "Naohiro Takahara",
             "Jassem Al-Houwaidi", "Jassem Al-Houwaidi",
             "Younis Mahmoud", "Younis Mahmoud", "Younis Mahmoud", "Younis Mahmoud"),
  country = c("Iran", "Iran", "Iran",
              "South Korea", "South Korea",
              "Japan", "Japan",
              "Kuwait", "Kuwait",
              "Iraq", "Iraq", "Iraq", "Iraq"),
  tournament = c("1996", "2000", "2004",
                 "2000", "2004",
                 "2000", "2004",
                 "1996", "2000",
                 "2004", "2007", "2011", "2015"),
  goals = c(8, 3, 3,
            6, 4,
            5, 4,
            6, 2,
            1, 4, 1, 2)
)

# soccer ball images
ac_top_scorers <- ac_top_scorers %>% 
  mutate(image = case_when(
    tournament == "2004" ~ "http://football-balls.com/ball_files/2004-asian-cup-adidas-roteiro-official-match-ball.png",
    tournament == "2007" ~ "http://football-balls.com/ball_files/2007-asian-cup-mercurial-veloci-official-match-ball.png",
    tournament == "2011" ~ "http://football-balls.com/ball_files/2011-asian-cup-nike-total-90-tracer-official-match-ball.png",
    tournament == "2015" ~ "http://football-balls.com/ball_files/2015-asian-cup-nike-ordem-2-official-match-ball.png",
    TRUE ~ "https://i.pinimg.com/originals/e7/d7/19/e7d7190f0b5b3abd4f6c17e2c7989ec3.jpg"
  ))
```


```{r}
ac_top_scorers %>% 
  ggplot(aes(x = player, y = goals,
             image = image)) +
  geom_isotype_col()
```







# Goals scored per tournament

```{r}
wiki_url <- "https://en.wikipedia.org"
acup_url <- "https://en.wikipedia.org/wiki/AFC_Asian_Cup"

cup_links <- read_html(acup_url) %>% 
  html_nodes("br+ i a") %>% 
  html_attr("href") %>% 
  .[-17:-18]


acup_df <- cup_links %>% 
  as_data_frame() %>% 
  mutate(cup = str_remove(value, "\\/wiki\\/") %>% str_replace_all("_", " ")) %>% 
  rename(link = value)



goals_info <- function(x) {
  goal_info <- wiki_url %>% 
    html_session() %>% 
    jump_to(x) %>% 
    html_nodes(".vcalendar") %>% 
    html_table(header = FALSE) %>% 
    flatten_df() %>% 
    spread(key = X1, value = X2) %>% 
    select(`Goals scored`) %>% 
    mutate(`Goals scored` = str_remove_all(`Goals scored`, pattern = ".*\\(") %>% 
             str_extract_all("\\d+\\.*\\d*") %>% as.numeric)
}

team_num_info <- function(x) {
  team_num_info <- wiki_url %>% 
    html_session() %>% 
    jump_to(x) %>% 
    html_nodes(".vcalendar") %>% 
    html_table(header = FALSE) %>% 
    flatten_df() %>% 
    spread(key = X1, value = X2) %>% 
    select(`Teams`) %>% 
    mutate(`Teams` = as.numeric(`Teams`))
}

match_num_info <- function(x) {
  match_num_info <- wiki_url %>% 
    html_session() %>% 
    jump_to(x) %>% 
    html_nodes(".vcalendar") %>% 
    html_table(header = FALSE) %>% 
    flatten_df() %>% 
    spread(key = X1, value = X2) %>% 
    janitor::clean_names() %>% 
    select(matches_played) %>% 
    mutate(matches_played = as.numeric(matches_played))
}


# all together:
goals_data <- acup_df %>% 
  mutate(goals_per_game = map(acup_df$link, goals_info) %>% unlist,
         team_num = map(acup_df$link, team_num_info) %>% unlist,
         match_num = map(acup_df$link, match_num_info) %>% unlist)

```

```{r}
ac_goals_df <- goals_data %>% 
  mutate(label = cup %>% str_extract("[0-9]+") %>% str_replace("..", "'"),
         team_num = case_when(
           is.na(team_num) ~ 16,
           TRUE ~ team_num
         )) %>% 
  arrange(cup) %>% 
  mutate(label = factor(label, label),
         team_num = c(4, 4, 4, 5, 6, 6, 10, 10, 10, 8, 12, 12, 16, 16, 16, 16))
```


```{r}
ac_goals_df %>% 
  ggplot(aes(x = label, y = goals_per_game, group = 1)) +
  geom_line() +
  geom_point() +
  #ggimage::geom_emoji(aes(image = '26bd'), size = 0.03) +
  labs(y = "Goals per Game",
       title = "Goals per Game throughout the Asian Cup.",
       subtitle = "Odd dip throughout the 80s to early 90s...")
  theme_minimal()
# annotate number of matches played on top as strip
# fit avg goals per game per each sequence of # of matches >>> kinda like splines
# add AFC logo? top right corner
# put top scorer country as geom_point?
# soccer ball emoji as geom_point?
# patchwork to include top scoring countries + other additional info
```







```{r}
wiki_url %>% 
  html_session() %>% 
  jump_to("/wiki/2015_AFC_Asian_Cup") %>% 
  html_nodes(".vcalendar") %>% 
  html_table(header = FALSE) %>% 
  flatten_df() %>% 
  spread(key = X1, value = X2) %>% 
  select(`Goals scored`) %>% 
  mutate(`Goals scored` = str_remove_all(`Goals scored`, pattern = ".*\\(") %>% 
           str_extract_all("\\d+\\.*\\d*") %>% as.numeric)
```


```{r}
###

one_cup <- "https://en.wikipedia.org/wiki/1968_AFC_Asian_Cup"

copa <- one_cup %>% 
  read_html() %>% 
  html_nodes(".vcalendar") %>% 
  html_table(header = FALSE) %>% 
  flatten_df() %>% 
  spread(key = X1, value = X2) %>% 
  janitor::clean_names() %>% 
  select(goals_scored) %>% 
  mutate(`Goals scored` = str_remove_all(`Goals scored`, pattern = ".*\\(") %>% 
           str_extract_all("\\d+\\.*\\d*") %>% as.numeric) # \\(.*)

```








# Asian Cup record

```{r}
# .navigation-not-searchable+ .jquery-tablesorter
acup_url <- "https://en.wikipedia.org/wiki/AFC_Asian_Cup"

acup_winners_raw <- acup_url %>% 
  read_html() %>% 
  html_nodes("#mw-content-text > div > table:nth-child(30)") %>% 
  html_table() %>% 
  flatten_df()

```

```{r}
acup_winners_clean <- acup_winners_raw %>% 
  janitor::clean_names() %>% 
  slice(1:8) %>% 
  select(-fourth_place, -total_top_four) %>% 
  separate(winners, into = c("first_num", "first_place_year"), sep = " ", extra = "merge") %>% 
  separate(runners_up, into = c("second_num", "second_place_year"), sep = " ", extra = "merge") %>% 
  separate(third_place, into = c("third_num", "third_place_year"), sep = " ", extra = "merge") %>% 
  mutate_all(funs(str_replace_all(., "–", "0"))) %>% 
  mutate_at(vars(contains("num")), funs(as.numeric)) %>% 
  mutate(team = if_else(team == "Israel1", "Israel", team)) %>% 
  gather(key = "key", value = "value", -team, 
         -first_place_year, -second_place_year, -third_place_year) %>% 
  mutate(key = case_when(
           key == "first_num" ~ "Champions",
           key == "second_num" ~ "Runners-up",
           key == "third_num" ~ "Third Place"
         ),
         key = key %>% fct_relevel(c("Champions", "Runners-up", "Third Place"))) %>% 
  # hack-ish solution?
  arrange(key, value) %>% 
  mutate(team = as_factor(team),
         order = row_number(),
         image = team %>% 
           countrycode(., origin = "country.name", destination = "iso2c"))
```

```{r, fig.width = 8, fig.height = 6}
a <- acup_winners_clean %>% 
  ggplot(aes(value, team, color = key)) +
  geom_point(size = 5) +
  scale_color_manual(values = c("Champions" = "#FFCC33",
                                "Runners-up" = "#999999",
                                "Third Place" = "#CC6600"),
                     guide = FALSE) +
  labs(x = "Number of Occurrence",
       title = "Winners & Losers of the Asian Cup!",
       subtitle = glue("
                       Ordered by number of Asian Cup(s) won.
                       Four-time Champions, Japan, only won their first in 1992!"),
       caption = glue("
                      Note: Israel was expelled by the AFC in 1974 while Australia joined the AFC in 2006.
                      Source: Wikipedia
                      By @R_by_Ryo")) +
  facet_wrap(~key) +
  theme_minimal() +
  theme(text = element_text(family = "Roboto Condensed"),
        title = element_text(size = 18),
        plot.subtitle = element_text(size = 12),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 12),
        plot.caption = element_text(hjust = 0, size = 10),
        panel.border = element_rect(fill = NA, colour = "grey20"),
        panel.grid.minor.x = element_blank(),
        strip.text = element_text(size = 16))

a +
  geom_flag(y = -2, aes(image = image), size = 0.15) +
  expand_limits(y = -2)

# insert_yaxis_grob()

#null_dev_env <- new.env(parent = emptyenv())
# set_null_device("pdf")
# cairo_pdf()
# ggdraw(add_sub(a, label = "Source: Wikipedia\nBy @R_by_Ryo", x = 0.95, size = 8))
# 
# Cairo::Cairo(1000, 750, "test.png", bg = "white")
# last_plot()
# dev.off()
```




## Working hours & Productivity

```{r}
acup_url <- "https://en.wikipedia.org/wiki/2019_AFC_Asian_Cup"

acup_kickoff <- acup_url %>% 
  read_html() %>% 
  html_nodes("time") %>% 
  html_text() %>% 
  as_data_frame()

# time
```

- calculate +90 minutes for entire game duration
- NOT count extra time or stoppage time
- cross-refernce with other local time zones
- count up total number of hours per each spectator country

```{r}

tz <- "Asia/"
acup_times_df <- acup_kickoff %>% 
  mutate(match_num = row_number(),
         match_type = if_else(between(match_num, 37, 51), "Knock-Out Stage", "Group Stage"),
         time = value %>% str_replace("\\(.*\\)", "")) %>% 
  mutate(time2 = dmy_hm(time),
         time_ac2 = force_tz(time2, "Asia/Dubai"), # time based in UTC +4
         time_jp = with_tz(time_ac2, tz = "Asia/Tokyo"), # UTC +4 time converted to Japan
         time_jp_end = time_jp + hm("2 0"),
         time_ac = with_tz(time2, tz = "America/New_York")) %>% # UTC +4 time to NYC
  mutate(diff = make_difftime(hour = 2),
         int = as.interval(diff, time_ac2),
         jp_work = as.interval(ymd_hms("2019-01-05 09:00:00"), ymd_hms("2019-01-05 12:00:00")))

jp_work %within% int

```

ymd_hms("2011-07-01 09:00:00", tz = "Pacific/Auckland")