---
title: "Untitled"
author: "RN7"
date: "March 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# % team goal involvement (チーム得点貢献度)

- inspiration: https://www.reddit.com/r/soccer/comments/b2wdfn/oc_which_players_are_most_involved_in_their_teams/
- first try with FC Tokyo
- then scale it up for all teams
- do 2018 season as only a few games into 2019 season...


# pkgs

```{r, message=FALSE, warning=FALSE}
pacman::p_load(tidyverse, polite, scales, ggimage, rvest, glue, extrafont, ggrepel)
loadfonts()
```

# just FC Tokyo

## scrape

```{r}
url <- "https://www.transfermarkt.com/fc-tokyo/leistungsdaten/verein/6631/reldata/JAP1%262017/plus/1"

# .items
# .items > tbody:nth-child(2)
session <- bow(url)

# fctokyo_table <- scrape(session) %>% 
#   html_nodes(".items > tbody:nth-child(2)") %>% flatten()
#   magrittr::extract(2)
#   html_table(fill = TRUE) %>% 
#   flatten_df()
  #magrittr::extract(1)
  
# tr.odd:nth-child(1) > td:nth-child(7)
  
player_name <- scrape(session) %>% 
  html_nodes("#yw1 .bilderrahmen-fixed") %>% 
  html_attr("title") 
  
num_goals <- scrape(session) %>% 
  html_nodes("td:nth-child(7)") %>% 
  html_text()

num_assists <- scrape(session) %>% 
  html_nodes("td:nth-child(8)") %>% 
  html_text()


resultados <- list(player_name, num_goals, num_assists)
col_names <- c("name", "goals", "assists")
```

## clean/tidy

```{r}
fctokyo_results <- resultados %>% 
  reduce(cbind) %>% 
  as_tibble() %>% 
  set_names(col_names)

fctokyo_df <- fctokyo_results %>% 
  mutate_at(.vars = c("goals", "assists"), ~str_replace(., "-", "0") %>% as.numeric) %>% 
  mutate(total_goals = sum(goals),
         total_assists = sum(assists),
         goal_contrib = goals/total_goals,
         assist_contrib = assists/total_goals)

```

## plot

```{r}
fctokyo_plot <- fctokyo_df %>% 
  ggplot(aes(assist_contrib, goal_contrib)) +
  geom_point() +
  scale_x_continuous(labels = percent) +
  scale_y_continuous(labels = percent) +
  labs(title = "Team Goal Involvement as Percentage of Total Club Goals",
       subtitle = "J-League 2018 Season",
       caption = glue("
                      Data: transfermarkt
                      By: @R_by_Ryo"),
       x = "Percentage of Club Goals Assisted",
       y = "Percentage of Club Goals Scored") +
  theme_minimal()

ggsave(plot = fctokyo_plot, filename = "../J-League 2018/fctokyo_plot.png")
```

## add_logo

```{r}
add_logo <- function(plot_path, logo_path, logo_position, logo_scale = 10){

    # Requires magick R Package https://github.com/ropensci/magick

    # Useful error message for logo position
    if (!logo_position %in% c("top right", "top left", "bottom right", "bottom left")) {
        stop("Error Message: Uh oh! Logo Position not recognized\n  Try: logo_positon = 'top left', 'top right', 'bottom left', or 'bottom right'")
    }

    # read in raw images
    plot <- magick::image_read(plot_path)
    logo_raw <- magick::image_read(logo_path)

    # get dimensions of plot for scaling
    plot_height <- magick::image_info(plot)$height
    plot_width <- magick::image_info(plot)$width

    # default scale to 1/10th width of plot
    # Can change with logo_scale
    logo <- magick::image_scale(logo_raw, as.character(plot_width/logo_scale))

    # Get width of logo
    logo_width <- magick::image_info(logo)$width
    logo_height <- magick::image_info(logo)$height

    # Set position of logo
    # Position starts at 0,0 at top left
    # Using 0.01 for 1% - aesthetic padding

    if (logo_position == "top right") {
        x_pos = plot_width - logo_width - 0.01 * plot_width
        y_pos = 0.01 * plot_height
    } else if (logo_position == "top left") {
        x_pos = 0.01 * plot_width
        y_pos = 0.01 * plot_height
    } else if (logo_position == "bottom right") {
        x_pos = plot_width - logo_width - 0.01 * plot_width
        y_pos = plot_height - logo_height - 0.01 * plot_height
    } else if (logo_position == "bottom left") {
        x_pos = 0.01 * plot_width
        y_pos = plot_height - logo_height - 0.01 * plot_height
    }

    # Compose the actual overlay
    magick::image_composite(plot, logo, offset = paste0("+", x_pos, "+", y_pos))

}
```


```{r}
logo_path <- "https://tmssl.akamaized.net//images/logo/normal/jap1.png?lm=1546692506"

add_logo(plot_path = glue("{here::here()}/J-League 2018/fctokyo_plot.png"),
         logo_path = logo_path, logo_position = "top right")
```




# all teams 

## scrape

```{r}
# #yw1 > table:nth-child(2) > tbody:nth-child(3) > tr:nth-child(1) > td:nth-child(2) > a:nth-child(1)

url <- "https://www.transfermarkt.com/j1-league/startseite/wettbewerb/JAP1/plus/?saison_id=2017"

session <- bow(url)

team_links <- scrape(session) %>% 
  html_nodes("#yw1 > table > tbody > tr > td.zentriert.no-border-rechts > a") %>% 
  html_attr("href")

team_links_df <- team_links %>% 
  enframe(name = NULL) %>% 
  separate(value, c(NA, "team_name", NA, NA, "team_num", NA, NA), sep = "/") %>% 
  mutate(link = glue("https://www.transfermarkt.com/{team_name}/leistungsdaten/verein/{team_num}/reldata/JAP1%262017/plus/1"))

# for each team link:

player_name_info <- function(link) {
  
  session <- bow(link)
  
  player_name_info <- scrape(session) %>% 
    html_nodes("#yw1 .bilderrahmen-fixed") %>% 
  html_attr("title") 
  
}

num_goals_info <- function(link) {
  
  session <- bow(link)
  
  num_goals_info <- scrape(session) %>% 
    html_nodes("td:nth-child(7)") %>% 
    html_text()
}

num_assists_info <- function(link) {
  
  session <- bow(link)
  
  num_assists_info <- scrape(session) %>% 
    html_nodes("td:nth-child(8)") %>% 
    html_text()
}

# BIG FUNCTION

jleague_stats_info <- function(link) {
  
  session <- bow(link)
  
  player_name_info <- scrape(session) %>% 
    html_nodes("#yw1 .bilderrahmen-fixed") %>% 
  html_attr("title") 

  num_goals_info <- scrape(session) %>% 
    html_nodes("td:nth-child(7)") %>% 
    html_text()

  num_assists_info <- scrape(session) %>% 
    html_nodes("td:nth-child(8)") %>% 
    html_text()
  
  resultados <- list(player_name_info, num_goals_info, num_assists_info)
  col_names <- c("name", "goals", "assists") 
  
  jleague_stats <- resultados %>% 
    reduce(cbind) %>% 
    as_tibble() %>% 
    set_names(col_names)
  
}


# all together:
# just 3 teams for now...
goal_contribution_df <- map2(.x = team_links_df$link[1:3], .y = team_links_df$team_name[1:3],
                             ~ jleague_stats_info(link = .x) %>% 
                               set_names(., nm = seq_along(.y)))
# mutate .y as team name

goal_contribution_df <- map(team_links_df$link[1:3], ~ jleague_stats_info) %>% 
  set_names(team_links_df$team_name[1:3])

# YES
the_big_data <- team_links_df[1:3,] %>% 
  ## map each team URL link to the data-getting function
  mutate(data = map(team_links_df$link[1:3], ~ jleague_stats_info(.x))) %>% 
  ## set names of each data list to team name
  mutate(data = data %>% set_names(team_links_df$team_name[1:3]))

the_big_data2$data$`vissel-kobe`$goals

# clean/tidy each team data list-column
the_big_data2 %>% 
  mutate(data = map(data, ~ .x %>% 
                      mutate_at(.vars = c("goals", "assists"), 
                                ~str_replace(., "-", "0") %>% as.numeric) %>% 
                      mutate(total_goals = sum(goals),
                             total_assists = sum(assists),
                             goal_contrib = goals/total_goals,
                             assist_contrib = assists/total_goals))) -> big_data3

big_data3$data


## save
saveRDS(goal_contribution_df, file = glue("{here::here()}/data/goal_contrib_df.RDS"))
```



- `mutate()` in similar way inside list >>> separate out and save each as separate dataframe
- make ggplot function >>> inputs: colors, team name in title